### ISSUE TITLE
Logout Functionality

### ISSUE THREAD

**Issue by vt-ombalakumar** [dakshsrivastava/Loglr#7]
I have integrated tumblr in application , integrated Loglr, works perfect on new project, I like to do sign out functionality in application, But don't know how to do..

**Comment by ArcherN9** [comment]
Loglr or Jumblr, either of the libraries does not support any mechanism for logging the user out. Intricately, 'logging out' is supposed to invalidate the tokens so they may not be used again.

Since Tumblr does not even have an API to log the user out, I suggest you delete the tokens, ensure there's no memory leak & inform user that he has been logged out. Loglr does not persistent any tokens, albeit I think Jumblr does. Check their code to see if they save the tokens in sharedPreferences the way Uber's SDK does.

**Comment by vt-ombalakumar** [comment]
they are not saving tokens i think.. but i will delete available oauth tokens and redirect user.. OK, thanks..
